apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
    - image: adservice
      context: src/adservice
    - image: cartservice
      context: src/cartservice
    - image: checkoutservice
      context: src/checkoutservice
    - image: currencyservice
      context: src/currencyservice
    - image: emailservice
      context: src/emailservice
    - image: frontend
      context: src/frontend
    - image: loadgenerator
      context: src/loadgenerator
    - image: paymentservice
      context: src/paymentservice
    - image: productcatalogservice
      context: src/productcatalogservice
    - image: recommendationservice
      context: src/recommendationservice
    - image: shippingservice
      context: src/shippingservice
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/**.yaml

