apiVersion: apps/v1
kind: Deployment
metadata:
  name: restservice
spec:
  selector:
    matchLabels:
      app: restservice
  template:
    metadata:
      labels:
        app: restservice
      annotations:
        sidecar.signadot.com/inject: rest
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: restservice
          ports:
            - containerPort: 5051
          # readinessProbe:
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:5050"]
          # livenessProbe:
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
            - name: PORT
              value: "5051"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice:5000"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CACHE_USER_THRESHOLD
              value: "35000"
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: restservice
spec:
  type: ClusterIP
  selector:
    app: restservice
  ports:
    - name: rest
      port: 5051
      targetPort: 5051
