on:
  pull_request:
    branches:
      - master
      - add-gha
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      checkoutservice: ${{ steps.filter.outputs.checkoutservice }}
    steps:
      # The paths-filter action requires a checkout step for push events.
      - if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'src/frontend/**'
            checkoutservice:
              - 'src/checkoutservice/**'

  build:
    name: Skaffold Docker build
    runs-on: ubuntu-20.04
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.20.0
        with:
          command: build -p frontend
          repository: docker.io/signadot
          tag: ${{ github.sha }}
