on:
  pull_request:
    branches:
      - master
      - add-gha
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      checkoutservice: ${{ steps.filter.outputs.checkoutservice }}
    steps:
      # The paths-filter action requires a checkout step for push events.
      - if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'src/frontend/**'
            checkoutservice:
              - 'src/checkoutservice/**'

  build-fe:
    needs: [ changes ]
    name: Skaffold Docker build
    runs-on: ubuntu-20.04
    if: ${{ needs.changes.outputs.frontend == 'false' }} 
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.19.0
        with:
          command: build -b frontend --file-output=tags.json
          repository: docker.io/signadot
          push: docker.io/signadot
          tag: ${{ github.sha }}
          filename: ${{ github.workspace }}/skaffold.yaml
          
      - name: Create FE Sandbox
        env:
          SIGNADOT_ORG: signadot
          IMAGE_TAG: ${{ github.sha }}
          SIGNADOT_API_KEY: ${{ secrets.SIGNADOT_API_KEY }}
        run: |
          docker run -i \
            -e SIGNADOT_ORG=${SIGNADOT_ORG} \
            -e SIGNADOT_API_KEY=${SIGNADOT_API_KEY} \
            signadot/signadot-cli \
            /signadot sandbox apply \
            --set image=signadot/frontend:${IMAGE_TAG} \
            --set gitsha=${IMAGE_TAG:0:6} \
            -f - \
            -o yaml \
            < ${GITHUB_WORKSPACE}/.signadot/sandbox-frontend-template.yaml \
            > ${GITHUB_WORKSPACE}/.signadot/sandbox-frontend-response.yaml
      
